### PR TITLE
Add support for heroku and also add requirement sinstallation step

### PR DESCRIPTION
**Pull request by IMMANUEL44**

### CODE REVIEW

**Comment by hitesh920** [comment]
@IMMANUEL44

**Comment by magneto261290** [comment]
I will never add heroku support in this repo. How much will you abuse a free service like heroku?
Because of too much abusing heroku started banning this repo.

**Comment by SamirJanaOfficial** [comment]
Great Job Buddy.. I support wht u said

**Comment by AmirulAndalib** [comment]
try zeet

**Pull request closed without merging**
