### PR TITLE
Update youtube_dl_download_helper.py

### PR DESCRIPTION
**Pull request by crazy-racer**

### CODE REVIEW

**Comment by magneto261290** [comment]
@crazy-racer do you know what you are trying to do? 😂😂

That's is already perfect man, and that is for audio then why selecting bestvideo?? 
is there any sense of doing this???

**Comment by discussiongrouppro** [comment]
Bro any video to deploy this python aria repo

**Comment by crazy-racer** [comment]
yes high quality videos download

**Comment by FristyFlakes** [comment]
It already has quality picker or aren't you following up the commits??

**Comment by magneto261290** [comment]
> yes high quality videos download

You don't know anything so plz don't make PR with these silly commits.

**Pull request closed without merging**
